#!/usr/bin/env python3
"""Assemble the master comparison table from the runs' own JSON.

The master table in LEADERBOARD.md was transcribed by hand across a dozen
runs and five metric files each. That is precisely the sort of arithmetic a
person gets wrong once and then quotes forever, so it is generated here
instead — every number read from the file the measuring script wrote.

Columns are chosen to answer the two questions the programme is actually
asking, side by side and with the confounds visible:

  · what the CODEC alone can do — k-fold RAPID r from single-month
    embeddings (with its bootstrap CI), and reconstruction skill;
  · what the frozen codec plus DYNAMICS can do — stage-2 z-space and
    decoded channel-space gains over persistence, and the transport probe
    from the transformer's section state;
  · and the two things that make runs incomparable if left unstated —
    the CHANNEL COUNT and the STEP COUNT. A 40k-step run next to a 15k-step
    one is not a fair fight, and the table has to say so rather than let a
    reader assume otherwise.

Usage:
    python3 ml/make_table.py                      # every run in ml/runs
    python3 ml/make_table.py --runs global14b global25 patch14
    python3 ml/make_table.py --markdown >> ml/LEADERBOARD.md
"""
import argparse
import json
import os
import sys

import torch

HERE = os.path.dirname(os.path.abspath(__file__))
RUNS = os.path.join(HERE, "runs")


def load(run, name):
    p = os.path.join(RUNS, run, name)
    if not os.path.exists(p):
        return None
    try:
        with open(p) as f:
            return json.load(f)
    except json.JSONDecodeError:
        return None


def kfold_of(run, target="rapid"):
    """probe_kfold writes ONE file for all runs it was asked about, and
    older runs also carry a per-run copy — check both, per-run first."""
    for path in (os.path.join(RUNS, run, "probe_kfold.json"),
                 os.path.join(RUNS, "probe_kfold.json")):
        if not os.path.exists(path):
            continue
        with open(path) as f:
            d = json.load(f)
        block = d.get(run, d).get(target) if isinstance(d, dict) else None
        if block:
            return block
    return None


def row(run):
    ck_path = os.path.join(RUNS, run, "pixelmae.pt")
    if not os.path.exists(ck_path):
        return None
    ck = torch.load(ck_path, map_location="cpu", weights_only=False)
    a = ck.get("args", {})
    tp = load(run, "trainprobe.json") or {}
    tm = load(run, "temporal.json") or {}
    kf = kfold_of(run) or {}
    ev = load(run, "eval.json") or {}

    def g(d, *path, default=None):
        for k in path:
            if not isinstance(d, dict) or k not in d:
                return default
            d = d[k]
        return d

    ci = kf.get("ci95") or [None, None]
    return {
        "run": run,
        "C": len(ck.get("chan", [])),
        "d_z": ck.get("d_z"),
        "patch": a.get("patch", 1),
        "steps": a.get("steps"),
        "kfold_r": kf.get("r_kfold_deseas"),
        "ci": f"[{ci[0]:+.2f},{ci[1]:+.2f}]" if ci[0] is not None else "—",
        "rmse": kf.get("rmse_sv"),
        "wind_only": g(kf, "wind_only_baseline", "r"),
        "lin_r": tp.get("linear_r_deseas"),
        "chan_pct": tp.get("chan_vs_persistence_pct"),
        "s2_z": g(tm, "z_t+1", "beats_persistence"),
        "s2_chan": g(tm, "chan_t+1", "pct_vs_persistence",
                     default=g(tm, "chan_t+1", "beats_persistence")),
        "s2_r": g(tm, "rapid_probe", "r_deseasonalised"),
        "codec_r": g(ev, "rapid_probe", "pearson_heldout_years"),
    }


def fmt(v, n=3):
    if v is None:
        return "—"
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, float):
        return f"{v:+.{n}f}" if abs(v) < 10 else f"{v:.{n}f}"
    return str(v)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", nargs="*", default=None)
    ap.add_argument("--markdown", action="store_true")
    a = ap.parse_args()
    runs = a.runs or sorted(
        r for r in os.listdir(RUNS)
        if os.path.exists(os.path.join(RUNS, r, "pixelmae.pt")))
    rows = [r for r in (row(x) for x in runs) if r]
    if not rows:
        sys.exit("no runs with checkpoints found")

    head = ["run", "C", "d_z", "patch", "steps", "k-fold r", "CI95",
            "RMSE Sv", "wind-only", "linear r", "chan% t+1", "stage2 r"]
    keys = ["run", "C", "d_z", "patch", "steps", "kfold_r", "ci",
            "rmse", "wind_only", "lin_r", "chan_pct", "s2_r"]
    table = [[fmt(r[k]) if k != "ci" else r[k] for k in keys] for r in rows]

    if a.markdown:
        print("| " + " | ".join(head) + " |")
        print("|" + "|".join("---" for _ in head) + "|")
        for t in table:
            print("| " + " | ".join(t) + " |")
        print("\n*Generated by `python3 ml/make_table.py --markdown`. "
              "`steps` and `C` are shown because they are what makes two rows "
              "incomparable: a 40k-step codec beside a 15k-step one is a "
              "difference in schedule, not in architecture.*")
    else:
        w = [max(len(head[i]), *(len(t[i]) for t in table)) for i in range(len(head))]
        print("  ".join(h.ljust(w[i]) for i, h in enumerate(head)))
        for t in table:
            print("  ".join(c.ljust(w[i]) for i, c in enumerate(t)))


if __name__ == "__main__":
    main()
