#!/usr/bin/env python3
"""Generate the offline test fixtures and the test registry.

Everything the smoke test and the unit tests read is GENERATED here, not
committed as binary blobs: a NetCDF file in git is a thing nobody can review.

    python tests/fixtures/make_fixtures.py [outdir]

Writes, under `outdir` (default tests/fixtures/generated):

    tiny/hello.dat                       an ordinary small file
    oisst/oisst-avhrr-v02r01.YYYYMMDD.nc three synthetic OISST days
    ncep/uflx.sfc.gauss.2001.nc          an NCEP-shaped file
    cmems/day_YYYYMMDD.nc                two CMEMS-shaped days (for bin025)
    sources_test.yaml                    a registry whose URLs are file:// URLs
                                         pointing at the files above
"""
from __future__ import annotations

import os
import sys

import numpy as np

OISST_DAYS = ["2001-12-29", "2001-12-30", "2001-12-31"]
CMEMS_DAYS = ["2003-07-01", "2003-07-02"]


def _nc(path):
    import netCDF4
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return netCDF4.Dataset(path, "w", format="NETCDF4")


def write_oisst_day(path: str, day: str, seed: int) -> None:
    """OISST's real shape: (time, zlev, lat, lon), cell-centre axes, an `ice`
    variable whose units say percent and whose valid_range is 0..1."""
    rng = np.random.default_rng(seed)
    lat = np.arange(-89.875, 90.0, 5.0)          # coarse, same convention
    lon = np.arange(0.125, 360.0, 5.0)
    with _nc(path) as ds:
        ds.createDimension("time", 1)
        ds.createDimension("zlev", 1)
        ds.createDimension("lat", len(lat))
        ds.createDimension("lon", len(lon))
        ds.createVariable("lat", "f4", ("lat",))[:] = lat
        ds.createVariable("lon", "f4", ("lon",))[:] = lon
        t = ds.createVariable("time", "f8", ("time",))
        t.units = "days since 1978-01-01 12:00:00"
        import datetime as dt
        y, m, d = (int(x) for x in day.split("-"))
        t[0] = (dt.date(y, m, d) - dt.date(1978, 1, 1)).days
        ds.createVariable("zlev", "f4", ("zlev",))[:] = [0.0]
        sst = ds.createVariable("sst", "f4", ("time", "zlev", "lat", "lon"))
        sst.units = "Celsius"
        sst[0, 0] = rng.normal(15.0, 5.0, (len(lat), len(lon))).astype("f4")
        ice = ds.createVariable("ice", "f4", ("time", "zlev", "lat", "lon"))
        ice.units = "percent"                     # the trap, faithfully
        ice.valid_range = np.array([0.0, 1.0], dtype="f4")
        ice[0, 0] = rng.uniform(0.0, 1.0, (len(lat), len(lon))).astype("f4")


def write_ncep(path: str) -> None:
    """T62-gaussian-shaped, 4x daily, descending latitude, lon 0..358.125."""
    rng = np.random.default_rng(7)
    lat = np.linspace(88.5, -88.5, 24)            # descending, like the real one
    lon = np.arange(0.0, 360.0, 15.0)
    with _nc(path) as ds:
        ds.createDimension("time", 8)             # two days at 4x daily
        ds.createDimension("lat", len(lat))
        ds.createDimension("lon", len(lon))
        ds.createVariable("lat", "f4", ("lat",))[:] = lat
        ds.createVariable("lon", "f4", ("lon",))[:] = lon
        t = ds.createVariable("time", "f8", ("time",))
        t.units = "hours since 1800-01-01 00:00:0.0"
        t.delta_t = "0000-00-00 06:00:00"
        t[:] = np.arange(8) * 6.0
        v = ds.createVariable("uflx", "f4", ("time", "lat", "lon"))
        v.units = "N/m^2"
        v[:] = rng.normal(0.0, 0.05, (8, len(lat), len(lon))).astype("f4")
        ds.title = "4x daily NMC reanalysis (synthetic fixture)"


def write_cmems_day(path: str, seed: int) -> None:
    """CMEMS's shape: latitude/longitude axes, (time, depth, lat, lon)."""
    rng = np.random.default_rng(seed)
    lat = np.arange(-2.0, 2.001, 0.0833333)
    lon = np.arange(-3.0, 3.001, 0.0833333)
    with _nc(path) as ds:
        ds.createDimension("time", 1)
        ds.createDimension("depth", 1)
        ds.createDimension("latitude", len(lat))
        ds.createDimension("longitude", len(lon))
        ds.createVariable("latitude", "f4", ("latitude",))[:] = lat
        ds.createVariable("longitude", "f4", ("longitude",))[:] = lon
        t = ds.createVariable("time", "f8", ("time",))
        t.units = "days since 1970-01-01"
        t[0] = 12235.0
        for name in ("uo", "vo"):
            v = ds.createVariable(name, "f4",
                                  ("time", "depth", "latitude", "longitude"))
            v[0, 0] = rng.normal(0.0, 0.3, (len(lat), len(lon))).astype("f4")


REGISTRY_TEMPLATE = """# GENERATED by tests/fixtures/make_fixtures.py — do not edit by hand.
# A registry whose "upstream" is a set of local file:// URLs, so the whole
# pipeline can be exercised with no network at all.
version: 1

hub:
  repo_id: test/local-hub
  repo_type: dataset
  commit_budget_per_hour: 0        # 0 = no commit-rate limiting in tests

hosts:
  testhost:
    max_lanes: 2
    min_gap_s: 0
    backoff_ladder_s: [0, 0, 0, 0]
    serves: the fixture files
    evidence: local
  testncei:
    max_lanes: 2
    min_gap_s: 0
    backoff_ladder_s: [0, 0, 0, 0]
    serves: the synthetic OISST days
    evidence: local
  testpsl:
    max_lanes: 1
    min_gap_s: 0
    backoff_ladder_s: [0, 0, 0, 0]
    serves: the synthetic NCEP file
    evidence: local
  testflaky:
    max_lanes: 1
    min_gap_s: 0
    backoff_ladder_s: [0, 0, 0, 0]
    serves: nothing — it always fails, to exercise the circuit breaker
    evidence: local

sources:
  - name: tiny
    tier: 0
    host: testhost
    mode: fetch
    fetcher: http
    chunk: file
    files: [hello.dat]
    url: "file://{root}/tiny/{{file}}"
    filename: "{{file}}"
    hub_prefix: tiny
    transform: passthrough
    expected_items: 1
    batch_files: 1
    bytes_wire: 32
    bytes_stored: 32
    notes: ["an ordinary small file over the http fetcher's file:// path"]

  - name: oisst
    tier: 0
    host: testncei
    mode: fetch
    fetcher: ncei_oisst_year
    chunk: year
    years: [2001, 2001]
    days: {days}
    expected_items: 1
    url: "file://{root}/oisst/oisst-avhrr-v02r01.{{ymd}}.nc"
    filename: oisst_daily_{{year}}.nc
    hub_prefix: oisst
    transform: oisst_year_fold
    batch_files: 1
    bytes_wire: 30000
    bytes_stored: 30000
    notes: ["three synthetic days folded into one year file"]

  - name: ncep
    tier: 0
    host: testpsl
    mode: fetch
    fetcher: http
    chunk: var_year
    vars: [uflx.sfc.gauss]
    years: [2001, 2001]
    expected_items: 1
    url: "file://{root}/ncep/{{file}}"
    filename: "{{var}}.{{year}}.nc"
    hub_prefix: ncep
    transform: passthrough
    batch_files: 1
    bytes_wire: 20000
    bytes_stored: 20000
    notes: ["an NCEP-shaped 4x-daily gaussian file"]

  - name: flaky
    tier: 0
    host: testflaky
    mode: fetch
    fetcher: transient_test
    chunk: file
    files: [a, b, c, d, e, f, g]
    url: "file://{root}/nowhere/{{file}}"
    filename: "{{file}}"
    hub_prefix: flaky
    transform: passthrough
    expected_items: 7
    batch_files: 1
    bytes_wire: 1
    bytes_stored: 1
    notes:
      - "ALWAYS fails, transiently. Five consecutive failures trip the lane's
         circuit breaker; the remaining items must come back `deferred` and
         the pipeline must still finish."
"""


def main(outdir: str) -> int:
    root = os.path.abspath(outdir)
    os.makedirs(root, exist_ok=True)

    os.makedirs(os.path.join(root, "tiny"), exist_ok=True)
    with open(os.path.join(root, "tiny", "hello.dat"), "w",
              encoding="utf-8") as fh:
        fh.write("beam_import fixture: an ordinary file\n")

    for i, day in enumerate(OISST_DAYS):
        write_oisst_day(
            os.path.join(root, "oisst",
                         f"oisst-avhrr-v02r01.{day.replace('-', '')}.nc"),
            day, seed=100 + i)

    write_ncep(os.path.join(root, "ncep", "uflx.sfc.gauss.2001.nc"))

    for i, day in enumerate(CMEMS_DAYS):
        write_cmems_day(
            os.path.join(root, "cmems", f"day_{day.replace('-', '')}.nc"),
            seed=200 + i)

    with open(os.path.join(root, "sources_test.yaml"), "w",
              encoding="utf-8") as fh:
        fh.write(REGISTRY_TEMPLATE.format(root=root, days=str(OISST_DAYS)))

    print(f"fixtures written to {root}")
    return 0


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1
                          else os.path.join(here, "generated")))
