// Per-slide sources: one array of {t: label, u: full URL} per slide, in deck order (46 entries).
// Appended to every speaker note by build.js (plain text) and rendered as clickable links on the
// notes pages (notes_deck.js) and on the Sources slide. Keep URLs full (https://) so they are
// clickable after a PDF export and survive a Google Slides import.
const P = {
  alphaearth: { t: "AlphaEarth Foundations paper", u: "https://arxiv.org/abs/2507.22291" },
  alphaearthBlog: { t: "DeepMind blog", u: "https://deepmind.google/blog/alphaearth-foundations-helps-map-our-planet-in-unprecedented-detail/" },
  alphaearthEE: { t: "Satellite Embedding dataset (Earth Engine)", u: "https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_SATELLITE_EMBEDDING_V1_ANNUAL" },
  tessera: { t: "TESSERA paper", u: "https://arxiv.org/abs/2506.20380" },
  tesseraCode: { t: "TESSERA code", u: "https://github.com/ucam-eo/tessera" },
  geotessera: { t: "GeoTessera embeddings", u: "https://github.com/ucam-eo/geotessera" },
  olmo: { t: "OlmoEarth paper", u: "https://arxiv.org/abs/2511.13655" },
  olmoBlog: { t: "Ai2 OlmoEarth blog", u: "https://allenai.org/blog/olmoearth-models" },
  olmoCode: { t: "OlmoEarth pretraining code", u: "https://github.com/allenai/olmoearth_pretrain" },
  olmo11: { t: "OlmoEarth v1.1", u: "https://huggingface.co/blog/allenai/olmoearth-v1-1" },
  olmo12: { t: "OlmoEarth v1.2", u: "https://allenai.org/papers/olmoearth-v1-2" },
  terramind: { t: "TerraMind paper", u: "https://arxiv.org/abs/2504.11171" },
  terramesh: { t: "TerraMesh dataset paper", u: "https://arxiv.org/abs/2504.11172" },
  terramindCode: { t: "TerraMind code", u: "https://github.com/IBM/terramind" },
  terramindHF: { t: "TerraMind weights (Hugging Face)", u: "https://huggingface.co/ibm-esa-geospatial" },
  prithvi: { t: "Prithvi-EO 2.0 paper", u: "https://arxiv.org/abs/2412.02732" },
  prithviCode: { t: "Prithvi-EO 2.0 code", u: "https://github.com/NASA-IMPACT/Prithvi-EO-2.0" },
  prithviHF: { t: "Prithvi weights and configs (Hugging Face)", u: "https://huggingface.co/ibm-nasa-geospatial" },
  granite: { t: "Granite-Geospatial-Ocean paper", u: "https://arxiv.org/abs/2509.21273" },
  graniteCode: { t: "ibm-granite/geospatial (code + config)", u: "https://github.com/ibm-granite/geospatial" },
  graniteHF: { t: "Granite-Geospatial-Ocean weights", u: "https://huggingface.co/ibm-granite/granite-geospatial-ocean" },
  oceansar1: { t: "OceanSAR-1 paper", u: "https://arxiv.org/abs/2504.06962" },
  oceansar1HF: { t: "OceanSAR-1 weights", u: "https://huggingface.co/galeio-research/OceanSAR-1" },
  oceansar2: { t: "OceanSAR-2 paper", u: "https://arxiv.org/abs/2601.07392" },
  copfm: { t: "Copernicus-FM paper", u: "https://arxiv.org/abs/2503.11849" },
  aurora: { t: "Aurora (Nature 2025)", u: "https://doi.org/10.1038/s41586-025-09005-y" },
  aifsOcean: { t: "AIFS surface ocean (ECMWF 2026)", u: "https://arxiv.org/abs/2604.25559" },
  pangaea: { t: "PANGAEA benchmark", u: "https://arxiv.org/abs/2412.04204" },
  geobench: { t: "GEO-Bench", u: "https://arxiv.org/abs/2306.03831" },
  geobench2: { t: "GEO-Bench-2", u: "https://arxiv.org/abs/2511.15658" },
  lcz: { t: "AlphaEarth vs TESSERA for Local Climate Zones", u: "https://arxiv.org/abs/2606.20034" },
  prithviWxC: { t: "Prithvi WxC", u: "https://arxiv.org/abs/2409.13598" },
  climax: { t: "ClimaX", u: "https://arxiv.org/abs/2301.10343" },
  oceannet: { t: "OceanNet", u: "https://arxiv.org/abs/2310.00813" },
  paradis: { t: "PARADIS — Learning to Advect", u: "https://arxiv.org/abs/2601.21151" },
  climode: { t: "ClimODE", u: "https://arxiv.org/abs/2404.10024" },
  neurallam: { t: "Neural-LAM", u: "https://arxiv.org/abs/2309.17370" },
  stretched: { t: "Stretched-grid ML weather", u: "https://arxiv.org/abs/2409.02891" },
  keisler: { t: "Keisler 2022", u: "https://arxiv.org/abs/2202.07575" },
  graphcast: { t: "GraphCast", u: "https://arxiv.org/abs/2212.12794" },
  pangu: { t: "Pangu-Weather", u: "https://arxiv.org/abs/2211.02556" },
  fuxi: { t: "FuXi", u: "https://arxiv.org/abs/2306.12873" },
  samudra: { t: "Samudra", u: "https://arxiv.org/abs/2412.03795" },
  samudrace: { t: "SamudrACE", u: "https://doi.org/10.1029/2025GL119340" },
  ace2som: { t: "ACE2-SOM", u: "https://arxiv.org/abs/2412.04418" },
  ace2nemo: { t: "ACE2-NEMO", u: "https://arxiv.org/abs/2603.28704" },
  aardvark: { t: "Aardvark Weather (Nature 2025)", u: "https://doi.org/10.1038/s41586-025-08897-0" },
  graphdop: { t: "GraphDOP", u: "https://arxiv.org/abs/2412.15687" },
  fourdvarnet: { t: "4DVarNet", u: "https://doi.org/10.1029/2023MS003609" },
  esfm: { t: "ESFM", u: "https://arxiv.org/abs/2605.00850" },
  penny: { t: "Penny & Hamill 2017, coupled DA (BAMS)", u: "https://doi.org/10.1175/BAMS-D-17-0036.1" },
  csirml6: { t: "CSIR-ML6 (Gregor et al. 2019)", u: "https://doi.org/10.5194/gmd-12-5113-2019" },
  canyonb: { t: "CANYON-B (Sauzède et al. 2017)", u: "https://doi.org/10.3389/fmars.2017.00128" },
  chelton: { t: "Chelton et al. 2011, global eddies", u: "https://doi.org/10.1016/j.pocean.2011.01.002" },
  emery: { t: "Emery et al. 1986, maximum cross-correlation (JGR)", u: "https://doi.org/10.1029/JC091iC11p12865" },
  perceiver: { t: "Perceiver IO", u: "https://arxiv.org/abs/2107.14795" },
  deser: { t: "Deser, Alexander & Timlin 2003 (SST persistence)", u: "https://doi.org/10.1175/1520-0442(2003)016<0057:UTPOSS>2.0.CO;2" },
  pujol: { t: "Pujol et al. 2016, DUACS DT2014", u: "https://doi.org/10.5194/os-12-1067-2016" },
  lellouche: { t: "Lellouche et al. 2021, GLORYS12", u: "https://doi.org/10.3389/feart.2021.698876" },
  zhang2019: { t: "Zhang et al. 2019, predictability limit", u: "https://doi.org/10.1175/JAS-D-18-0269.1" },
  cfl: { t: "Courant, Friedrichs & Lewy 1928", u: "https://doi.org/10.1007/BF01448839" },
  // Earth 2
  paper: { t: "Earth 2 paper (v8, PDF)", u: "https://github.com/blauewelt/earth/blob/main/ml/paper/paper.pdf" },
  mlclaude: { t: "ml/CLAUDE.md (replication rules, §3b)", u: "https://blauewelt.github.io/earth/docs.html?f=ml/CLAUDE.md" },
  explorer: { t: "Dependency-Cone Explorer", u: "https://blauewelt.github.io/earth/ml/figures/dependency_cone_explorer.html" },
  proposal: { t: "Generic-embedding input proposal (full note)", u: "https://blauewelt.github.io/earth/docs.html?f=ml/figures/geofm_survey/GENERIC_EMBEDDING_INPUTS.md" },
  surveyNotes: { t: "Survey notes", u: "https://blauewelt.github.io/earth/docs.html?f=ml/figures/geofm_survey/SURVEY_NOTES.md" },
  e069: { t: "E-069 plan — two stencils, one cone", u: "https://blauewelt.github.io/earth/docs.html?f=ml/plans/E069_cone_codec.md" },
  e069log: { t: "E-069 in the experiment log", u: "https://blauewelt.github.io/earth/docs.html?f=ml/EXPERIMENTS.md#e-069" },
  // datasets — imagery and radar
  s2: { t: "Sentinel-2", u: "https://sentinels.copernicus.eu/copernicus/sentinel-2" },
  s2ext: { t: "Sentinel-2A extension to end-2026", u: "https://sentinels.copernicus.eu/-/sentinel-2a-extension-campaign-prolonged-until-the-end-of-2026" },
  s1: { t: "Sentinel-1", u: "https://sentinels.copernicus.eu/copernicus/sentinel-1" },
  s1reconf: { t: "Sentinel-1 orbital reconfiguration (S1A end)", u: "https://sentinels.copernicus.eu/-/sentinel-1-orbital-reconfiguration-dates" },
  s1d: { t: "Sentinel-1D data opening", u: "https://sentinels.copernicus.eu/-/sentinel-1d-user-data-opening-and-future-plans" },
  landsat: { t: "Landsat Collection 2 Level-2", u: "https://www.usgs.gov/landsat-missions/landsat-collection-2-level-2-science-products" },
  s3: { t: "Sentinel-3", u: "https://sentinels.copernicus.eu/copernicus/sentinel-3" },
  modisviirs: { t: "NASA MODIS → VIIRS transition", u: "https://www.earthdata.nasa.gov/data/alerts-outages/transition-from-modis-viirs" },
  viirs: { t: "VIIRS", u: "https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/viirs/" },
  snpp: { t: "NOAA: Suomi-NPP data end 1 Nov 2026", u: "https://www.nesdis.noaa.gov/news/cessation-of-suomi-national-polar-orbiting-partnership-s-npp-data-users-onafter-november-01-2026" },
  abi: { t: "GOES ABI", u: "https://www.goes-r.gov/spacesegment/abi.html" },
  goes19: { t: "GOES-19 operational", u: "https://www.nesdis.noaa.gov/news/noaas-goes-19-now-operational-goes-east-providing-critical-new-data-forecasters" },
  fci: { t: "MTG FCI (WMO OSCAR)", u: "https://space.oscar.wmo.int/instruments/view/fci" },
  ahi: { t: "Himawari AHI", u: "https://www.data.jma.go.jp/mscweb/en/himawari89/space_segment/spsg_ahi.html" },
  s6: { t: "Sentinel-6", u: "https://documentation.dataspace.copernicus.eu/Data/SentinelMissions/Sentinel6.html" },
  jason3: { t: "Jason-3 (AVISO)", u: "https://www.aviso.altimetry.fr/en/missions/current-missions/jason-3.html" },
  swot: { t: "SWOT (PO.DAAC)", u: "https://podaac.jpl.nasa.gov/SWOT" },
  ascat: { t: "ASCAT winds (OSI SAF)", u: "https://osi-saf.eumetsat.int/products/osi-104-b" },
  amsr2: { t: "AMSR2 sea ice (NSIDC)", u: "https://nsidc.org/data/au_si12/versions/1" },
  amsr3: { t: "NOAA: AMSR2 → AMSR3", u: "https://www.nesdis.noaa.gov/news/decommissioning-of-advanced-microwave-scanning-radiometer-amsr2-products-and-transition-amsr3-products" },
  ssmis: { t: "NSIDC: SSMIS sunsets, AMSR2 rises", u: "https://nsidc.org/sea-ice-today/analyses/ssmis-sunsets-amsr2-rises" },
  smap: { t: "SMAP (NSIDC)", u: "https://nsidc.org/data/smap/data" },
  smos: { t: "SMOS (ESA)", u: "https://earth.esa.int/eogateway/missions/smos" },
  imerg: { t: "GPM IMERG", u: "https://gpm.nasa.gov/data/imerg" },
  mrms: { t: "MRMS", u: "https://www.nssl.noaa.gov/projects/mrms/" },
  opera: { t: "EUMETNET OPERA", u: "https://www.eumetnet.eu/activities/observations-programme/current-activities/opera/" },
  gedi: { t: "GEDI", u: "https://gedi.umd.edu/" },
  icesat2: { t: "ICESat-2", u: "https://icesat-2.gsfc.nasa.gov/science/specs" },
  cygnss: { t: "CYGNSS", u: "https://podaac.jpl.nasa.gov/CYGNSS" },
  glm: { t: "GOES GLM", u: "https://www.goes-r.gov/spacesegment/glm.html" },
  s5p: { t: "Sentinel-5P TROPOMI", u: "https://sentinel.esa.int/web/sentinel/missions/sentinel-5p" },
  oco2: { t: "OCO-2", u: "https://ocov2.jpl.nasa.gov/" },
  // atmosphere
  era5: { t: "ERA5 (CDS)", u: "https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels" },
  era5doc: { t: "ERA5 documentation (SST/sea ice prescribed; 12 h 4D-Var)", u: "https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation" },
  era5land: { t: "ERA5-Land (CDS)", u: "https://cds.climate.copernicus.eu/datasets/reanalysis-era5-land" },
  ecmwfOpen: { t: "ECMWF open data", u: "https://www.ecmwf.int/en/forecasts/datasets/open-data" },
  gfs: { t: "GFS (NCEI)", u: "https://www.ncei.noaa.gov/products/weather-climate-models/global-forecast" },
  merra2: { t: "MERRA-2", u: "https://gmao.gsfc.nasa.gov/reanalysis/MERRA-2/" },
  isd: { t: "ISD stations", u: "https://www.ncei.noaa.gov/products/land-based-station/integrated-surface-database" },
  ghcnd: { t: "GHCN-Daily", u: "https://www.ncei.noaa.gov/products/land-based-station/global-historical-climatology-network-daily" },
  igra: { t: "IGRA radiosondes", u: "https://www.ncei.noaa.gov/products/weather-balloon/integrated-global-radiosonde-archive" },
  icoads: { t: "ICOADS", u: "https://icoads.noaa.gov/" },
  ndbc: { t: "NDBC buoys", u: "https://www.ndbc.noaa.gov/" },
  gloss: { t: "GLOSS tide gauges", u: "https://gloss-sealevel.org/" },
  maiac: { t: "MAIAC AOD (MCD19A2)", u: "https://lpdaac.usgs.gov/products/mcd19a2v061/" },
  // ocean
  ostia: { t: "OSTIA SST (Copernicus Marine)", u: "https://data.marine.copernicus.eu/product/SST_GLO_SST_L4_NRT_OBSERVATIONS_010_001" },
  mur: { t: "MUR SST (PO.DAAC)", u: "https://podaac.jpl.nasa.gov/dataset/MUR-JPL-L4-GLOB-v4.1" },
  duacs: { t: "DUACS sea level L4 (Copernicus Marine)", u: "https://data.marine.copernicus.eu/product/SEALEVEL_GLO_PHY_L4_NRT_008_046" },
  duacsDesc: { t: "DUACS system description (windows)", u: "https://duacs.cls.fr/duacs-system-description/merged-gridded-l4-products-generation/" },
  glorys: { t: "GLORYS12 (Copernicus Marine)", u: "https://data.marine.copernicus.eu/product/GLOBAL_MULTIYEAR_PHY_001_030" },
  cmemsFc: { t: "Copernicus global analysis/forecast", u: "https://data.marine.copernicus.eu/product/GLOBAL_ANALYSISFORECAST_PHY_001_024" },
  argo: { t: "Argo", u: "https://argo.ucsd.edu/" },
  bgcargo: { t: "BGC-Argo", u: "https://biogeochemical-argo.org/" },
  oceanops: { t: "OceanOPS (live platform counts)", u: "https://www.ocean-ops.org/" },
  drifters: { t: "Global Drifter Program", u: "https://www.aoml.noaa.gov/phod/gdp/" },
  oscar: { t: "OSCAR currents", u: "https://podaac.jpl.nasa.gov/dataset/OSCAR_L4_OC_NRT_V2.0" },
  occci: { t: "ESA OC-CCI", u: "https://climate.esa.int/en/projects/ocean-colour/" },
  globcolour: { t: "GlobColour L3 (Copernicus Marine)", u: "https://data.marine.copernicus.eu/product/OCEANCOLOUR_GLO_BGC_L3_MY_009_107" },
  pace: { t: "PACE", u: "https://pace.oceansciences.org/" },
  socat: { t: "SOCAT", u: "https://socat.info/" },
  cmemsCarbon: { t: "Copernicus surface carbon", u: "https://data.marine.copernicus.eu/product/MULTIOBS_GLO_BGC_CARBON_SURFACE_MYNRT_015_008" },
  osisafIce: { t: "OSI SAF sea-ice products", u: "https://osi-saf.eumetsat.int/products/sea-ice-products" },
  gebco: { t: "GEBCO", u: "https://www.gebco.net/" },
  en4: { t: "EN4 (Met Office)", u: "https://www.metoffice.gov.uk/hadobs/en4/" },
  oceansites: { t: "OceanSITES", u: "http://www.oceansites.org/" },
  gtmba: { t: "GTMBA / TAO moorings", u: "https://www.pmel.noaa.gov/gtmba/" },
  // land / static
  copdem: { t: "Copernicus DEM", u: "https://dataspace.copernicus.eu/explore-data/data-collections/copernicus-contributing-missions/collections-description/COP-DEM" },
  worldcover: { t: "ESA WorldCover", u: "https://esa-worldcover.org/" },
  dynamicworld: { t: "Dynamic World", u: "https://dynamicworld.app/" },
  ccilc: { t: "ESA CCI land cover", u: "https://climate.esa.int/en/projects/land-cover/" },
  soilgrids: { t: "SoilGrids", u: "https://www.isric.org/explore/soilgrids" },
  cglLai: { t: "Copernicus Global Land LAI 300 m", u: "https://land.copernicus.eu/en/products/vegetation/leaf-area-index-v2-0-300m" },
  troposif: { t: "TROPOSIF", u: "https://s5p-troposif.noveltis.fr/" },
  mod11: { t: "MODIS LST (MOD11A1)", u: "https://lpdaac.usgs.gov/products/mod11a1v061/" },
  mod13: { t: "MODIS NDVI/EVI (MOD13Q1)", u: "https://lpdaac.usgs.gov/products/mod13q1v061/" },
  mod16: { t: "MODIS ET (MOD16A2GF)", u: "https://www.earthdata.nasa.gov/data/catalog/lpcloud-mod16a2gf-061" },
  gleam: { t: "GLEAM", u: "https://www.gleam.eu/" },
  ccism: { t: "ESA CCI soil moisture", u: "https://climate.esa.int/en/projects/soil-moisture/" },
  hsaf: { t: "H SAF (ASCAT soil moisture)", u: "https://hsaf.meteoam.it/" },
  firms: { t: "FIRMS active fire", u: "https://firms.modaps.eosdis.nasa.gov/" },
  mod10: { t: "MODIS snow (MOD10A1)", u: "https://nsidc.org/data/mod10a1/versions/61" },
  ims: { t: "IMS snow/ice", u: "https://nsidc.org/data/g02156" },
  rgi: { t: "RGI glacier inventory", u: "https://www.glims.org/rgi_user_guide/welcome.html" },
  grace: { t: "GRACE/GRACE-FO JPL mascons", u: "https://grace.jpl.nasa.gov/data/get-data/jpl_global_mascons/" },
  fluxnet: { t: "FLUXNET", u: "https://fluxnet.org/" },
  icos: { t: "ICOS", u: "https://www.icos-cp.eu/" },
  ameriflux: { t: "AmeriFlux", u: "https://ameriflux.lbl.gov/" },
  grdc: { t: "GRDC river discharge", u: "https://grdc.bafg.de/" },
  glofas: { t: "GloFAS", u: "https://ewds.climate.copernicus.eu/datasets/cems-glofas-historical" },
  hydroweb: { t: "Hydroweb.next", u: "https://hydroweb.next.theia-land.fr/" },
  worldpop: { t: "WorldPop", u: "https://www.worldpop.org/" },
  ghsl: { t: "GHSL", u: "https://human-settlement.emergency.copernicus.eu/" },
  blackmarble: { t: "VIIRS Black Marble", u: "https://www.earthdata.nasa.gov/data/projects/black-marble" },
  ethCanopy: { t: "ETH global canopy height", u: "https://langnico.github.io/globalcanopyheight/" },
  metaCanopy: { t: "Meta/WRI 1 m canopy height", u: "https://registry.opendata.aws/dataforgood-fb-forests/" },
  // --- what feeds the cone codec today (slide 45) ---
  glorysProduct: { t: "GLORYS12V1 product page (Copernicus Marine)", u: "https://data.marine.copernicus.eu/product/GLOBAL_MULTIYEAR_PHY_001_030/description" },
  oisstPsl: { t: "NOAA OISST v2.1 (NOAA PSL)", u: "https://psl.noaa.gov/data/gridded/data.noaa.oisst.v2.highres.html" },
  rgArgo: { t: "Roemmich–Gilson Argo climatology (Scripps)", u: "https://sio-argo.ucsd.edu/RG_Climatology.html" },
  ncepR1: { t: "NCEP/NCAR Reanalysis 1 (NOAA PSL)", u: "https://psl.noaa.gov/data/gridded/data.ncep.reanalysis.html" },
  rapidData: { t: "RAPID-MOCHA-WBTS 26.5° N data", u: "https://rapid.ac.uk/data/data-download" },
  floridaCable: { t: "Florida Current cable transport (NOAA AOML)", u: "https://www.aoml.noaa.gov/phod/floridacurrent/" },
  dataLadder: { t: "ml/plans/DATA_LADDER.md (source)", u: "https://github.com/blauewelt/earth/blob/main/ml/plans/DATA_LADDER.md" },
  e069blob: { t: "ml/plans/E069_cone_codec.md (source)", u: "https://github.com/blauewelt/earth/blob/main/ml/plans/E069_cone_codec.md" },
  // --- El Niño 2026 (slide 48) ---
  cpcEnso: { t: "CPC ENSO diagnostic discussion, 13 Aug 2026", u: "https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso_disc_aug2026/ensodisc.shtml" },
  iriPlume: { t: "IRI/CPC ENSO forecast plume", u: "https://iri.columbia.edu/our-expertise/climate/forecasts/enso/current/" },
  pmelWwv: { t: "PMEL Warm Water Volume / 20 °C isotherm", u: "https://www.pmel.noaa.gov/tao/wwv/data/" },
  godas: { t: "GODAS ocean analysis (NOAA PSL)", u: "https://psl.noaa.gov/data/gridded/data.godas.html" },
  interpOlr: { t: "NOAA interpolated outgoing longwave radiation", u: "https://psl.noaa.gov/data/gridded/data.interp_OLR.html" },
  oni: { t: "Oceanic Niño Index (NOAA CPC)", u: "https://origin.cpc.ncep.noaa.gov/products/analysis_monitoring/ensostuff/ONI_v5.php" },
  pslIndices: { t: "NOAA PSL climate indices", u: "https://psl.noaa.gov/data/climateindices/list/" },
  mei: { t: "Multivariate ENSO Index v2 (NOAA PSL)", u: "https://psl.noaa.gov/enso/mei/" },
  rmm: { t: "RMM Madden–Julian Oscillation index (BoM)", u: "https://www.bom.gov.au/climate/mjo/" },
  ccmp: { t: "CCMP ocean vector winds (REMSS)", u: "https://www.remss.com/measurements/ccmp/" },
  oscarFinal: { t: "OSCAR L4 final v2.0 (PO.DAAC)", u: "https://podaac.jpl.nasa.gov/dataset/OSCAR_L4_OC_FINAL_V2.0" },
  catalogJson: { t: "data/catalog.json — the 274-record catalog (source)", u: "https://github.com/blauewelt/earth/blob/main/data/catalog.json" },
  catalogDoc: { t: "docs/CATALOG.md — the catalog in prose", u: "https://blauewelt.github.io/earth/docs.html?f=docs/CATALOG.md" },
  coneDataEnso: { t: "CONE_DATA_AND_ENSO.md — the companion page", u: "https://blauewelt.github.io/earth/docs.html?f=ml/figures/geofm_survey/CONE_DATA_AND_ENSO.md" },
};
const S = (...k) => k.map(x => P[x]);
const modelSix = S("alphaearth", "tessera", "olmo", "terramind", "prithvi", "granite");
module.exports = [
  /* 1 */ S("surveyNotes", "paper"),
  /* 2 */ S("alphaearth", "tessera", "olmo", "terramind", "prithvi", "granite"),
  /* 3 */ S("alphaearth", "alphaearthBlog", "alphaearthEE"),
  /* 4 */ S("alphaearth"),
  /* 5 */ S("alphaearth"),
  /* 6 */ S("alphaearth"),
  /* 7 */ S("alphaearth"),
  /* 8 */ S("alphaearth", "alphaearthEE"),
  /* 9 */ S("tessera", "tesseraCode", "geotessera"),
  /* 10 */ S("olmo", "olmoBlog", "olmoCode", "olmo11", "olmo12"),
  /* 11 */ S("terramind", "terramesh", "terramindCode", "terramindHF"),
  /* 12 */ S("prithvi", "prithviCode", "prithviHF"),
  /* 13 */ S("granite", "graniteCode", "graniteHF"),
  /* 14 */ modelSix,
  /* 15 */ modelSix,
  /* 16 */ [...S("alphaearthEE", "geotessera", "olmoCode", "terramindHF", "prithviHF", "graniteHF")],
  /* 17 */ S("granite", "oceansar1", "oceansar2", "copfm", "aurora", "aifsOcean", "paper"),
  /* 18 */ S("aifsOcean", "samudra", "samudrace", "granite", "esfm", "paper"),
  /* 19 */ S("olmo", "tessera"),
  /* 20 */ S("olmo", "terramind", "pangaea"),
  /* 21 */ S("tessera", "lcz", "olmo", "alphaearth"),
  /* 22 */ S("granite", "oceansar1", "oceansar2"),
  /* 23 */ S("olmo", "terramind", "prithvi", "tessera", "geobench", "geobench2", "lcz", "granite", "oceansar1"),
  /* 24 */ S("paper", "mlclaude", "tessera", "alphaearth"),
  /* 25 */ S("tessera", "paper", "mlclaude", "e069"),
  /* 26 */ S("explorer", "chelton", "cfl"),
  /* 27 */ S("explorer", "chelton", "paper", "mlclaude"),
  /* 28 */ S("explorer", "chelton"),
  /* 29 */ S("explorer"),
  /* 30 */ S("explorer"),
  /* 31 */ S("explorer", "chelton", "paper", "mlclaude"),
  /* 32 */ S("cfl", "oceannet", "paradis", "climode", "neurallam", "stretched", "keisler", "graphcast", "pangu", "fuxi", "climax", "aurora", "prithviWxC", "samudra", "ace2som"),
  /* 33 */ S("samudra", "samudrace", "ace2som", "ace2nemo", "aifsOcean", "aurora", "aardvark", "graphdop", "fourdvarnet", "esfm", "copfm", "prithviWxC", "alphaearth", "csirml6", "canyonb", "granite", "penny"),
  /* 34 */ S("proposal", "era5doc", "duacsDesc", "lellouche"),
  /* 35 */ S("proposal", "s2", "s2ext", "s1", "s1reconf", "s1d", "landsat", "s3", "viirs", "modisviirs", "abi", "goes19", "fci", "ahi"),
  /* 36 */ S("proposal", "swot", "s6", "jason3", "mrms", "opera", "glm", "gedi", "icesat2", "s5p", "oco2", "ostia", "mur", "duacs", "imerg", "ascat", "amsr2", "osisafIce", "smap", "era5", "era5doc", "ecmwfOpen", "gfs", "argo", "bgcargo", "oceanops", "drifters", "gtmba", "oceansites", "glorys", "cmemsFc"),
  /* 37 */ S("proposal", "occci", "globcolour", "pace", "socat", "cmemsCarbon", "cglLai", "troposif", "mod11", "mod16", "gleam", "hsaf", "mod10", "ims", "firms", "grace", "grdc", "glofas", "hydroweb", "fluxnet", "icos", "ameriflux", "isd", "ghcnd", "igra", "icoads", "ndbc", "gloss", "copdem", "gebco", "worldcover", "ccilc", "soilgrids", "ethCanopy", "metaCanopy", "rgi", "worldpop", "ghsl", "blackmarble", "maiac", "merra2"),
  /* 38 */ S("proposal", "duacsDesc", "pujol", "lellouche", "era5doc", "ostia", "globcolour", "dynamicworld", "mod13", "oscar"),
  /* 39 */ S("proposal", "explorer", "chelton", "deser", "zhang2019"),
  /* 40 */ S("proposal", "perceiver", "aifsOcean", "paper"),
  /* 41 */ S("proposal", "emery", "paradis", "drifters", "glorys"),
  /* 42 */ S("proposal", "paper", "mlclaude"),
  /* 43 */ S("proposal", "paper", "mlclaude", "prithvi"),
  /* 44 */ S("e069", "e069log", "proposal", "chelton", "deser", "emery", "perceiver", "glorys", "mlclaude"),
  /* 45 — what feeds the cone codec today */ S("glorysProduct", "oisstPsl", "rgArgo", "ncepR1", "rapidData", "floridaCable", "dataLadder", "e069blob", "e069", "coneDataEnso", "proposal", "mlclaude"),
  /* 46 */ S("proposal", "paper", "mlclaude", "cmemsFc"),
  /* 47 */ S("proposal", "s1reconf", "s1d", "s2ext", "modisviirs", "snpp", "ssmis", "amsr3", "s6", "occci", "ccism", "en4", "grdc", "opera", "gleam", "ecmwfOpen"),
  /* 48 — El Niño 2026 */ S("cpcEnso", "iriPlume", "pmelWwv", "godas", "interpOlr", "oni", "pslIndices", "mei", "rmm", "ccmp", "oscarFinal", "catalogJson", "catalogDoc", "coneDataEnso"),
  /* 49 */ S("surveyNotes", "proposal", "paper"),
];
module.exports.P = P;
