#!/usr/bin/env python3
"""E-070 / E-071 Phase E · the cone on a GLOBE, and on a three-group tensor.

Two changes to `ml/cone_sampler.py` are under test here, and both are changes
of the same kind: the sampler stops asserting a property of the North Atlantic
window and starts READING the property off the tensor it was handed.

  1. **The dateline.** Whether the cell west of column 0 is column W-1 is a
     fact about the longitude axis — `W * dlon == 360` means the axis closes —
     not a policy. So `ConeSampler.wrap` is measured in the constructor: false
     for family 4's 481 x 0.25 deg = 120 deg window, where a wrap would put
     the Iberian shelf one cell west of Florida, and true for family 7's
     1440 x 0.25 deg = 360 deg globe, where refusing it would cut the Pacific
     in half. Latitude is still clipped and never wrapped.

  2. **Three groups at two resolutions.** Family 7 is `g025` (0.25 deg, 7
     channels), `g100` (1 deg, 14) and `rg100` (1 deg, 32, live Argo bins
     only). The cone is placed on the dense grid; a coarse channel is read at
     the coarse cell E-070 §1's lookup names; a live-bins channel is a miss
     token at every bin its group did not write. The TOKEN SCHEMA does not
     move — same `vals`/`obs`/`valid`, same count — because the group change
     is about where a value comes from, not how many there are.

The North Atlantic path must be BIT-IDENTICAL to what it was before either
change. That is pinned below by a digest taken from the pre-change code and
written into this file, not recomputed from the current one — a reference
generated by the thing it certifies certifies nothing.

    python3 -m pytest -q tests/test_cone_global.py

The multi-group half runs against a real family-7 tensor built by
`ml/build_family7.py --smoke`: synthetic sources, the whole builder, the full
721 x 1440 grid and five pentad bins, about twenty seconds. A toy GroupSet
assembled by hand would test this file's own idea of the layout; the smoke
tensor tests the layout the builder writes.
"""
import hashlib
import os
import sys

import numpy as np
import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ML = os.path.join(ROOT, "ml")
if ML not in sys.path:
    sys.path.insert(0, ML)

import cone                                                        # noqa: E402
from cone_sampler import (ConeSampler, Group, GroupSet,            # noqa: E402
                          group_time)

# The digest of `ConeSampler.sample`'s ENTIRE output over the fixture below,
# taken from the code as it stood BEFORE the wrap and the group support were
# written (2026-09-04). Every array, its dtype, its shape and its bytes.
NA_DIGEST = "6042073e1a20f00d9e233e16570920ba366dfe359fe13a97eaab51c8162d0180"

NA_CHANS = ["cur_speed", "log_mld", "ssh", "tau_x", "tau_y", "tau_x_std",
            "tau_y_std", "sst", "cur_u", "cur_v", "rg_t300", "rg_s300"]


def _na_fixture():
    """Family 4's window (lat 0..70, lon -100..20 at 0.25 deg), random."""
    rng = np.random.default_rng(20260904)
    T, H, W, C = 40, 281, 481, len(NA_CHANS)
    X = rng.normal(size=(T, H, W, C)).astype(np.float32)
    X[rng.random(X.shape) < 0.05] = np.nan
    lats = 0.0 + 0.25 * np.arange(H)
    lons = -100.0 + 0.25 * np.arange(W)
    return X, lats, lons


def _na_anchors():
    rng = np.random.default_rng(7)
    a = np.stack([rng.integers(6, 38, 64), rng.integers(0, 281, 64),
                  rng.integers(0, 481, 64)], axis=1).astype(np.int64)
    a[0] = [20, 140, 0]                       # hard against the west edge
    a[1] = [20, 140, 480]                     # hard against the east edge
    a[2] = [20, 0, 240]                       # hard against the south edge
    a[3] = [20, 280, 240]                     # hard against the north edge
    return a


def _digest(out):
    h = hashlib.sha256()
    for k in sorted(out):
        a = np.ascontiguousarray(out[k])
        h.update(k.encode())
        h.update(str(a.dtype).encode())
        h.update(str(a.shape).encode())
        h.update(a.tobytes())
    return h.hexdigest()


# ============================================================ 1. the wrap ==
def test_wrap_is_measured_from_the_lon_axis_not_declared():
    """`wrap` is a property of the tensor, and there is no flag to get wrong.

    481 columns of 0.25 deg span 120.25 deg and the axis does not close; 1440
    of them span exactly 360 and it does. The constructor computes that, so a
    caller cannot hand the North Atlantic window a `wrap=True` and cannot
    forget it on the globe.
    """
    for W, lon0, want in ((481, -100.0, False), (1440, -180.0, True),
                          (720, -180.0, False),   # 0.5 deg would close, 0.25
                                                  # does not
                          (360, -180.0, False)):
        X = np.zeros((2, 3, W, 1), np.float32)
        s = ConeSampler(X, np.isfinite(X), [0.0, 0.25, 0.5],
                        lon0 + 0.25 * np.arange(W), ["ssh"], L_in=1)
        assert s.wrap is want, (W, lon0)
    # and a HALF-degree global axis closes too — the rule is the arithmetic,
    # not the number 1440
    X = np.zeros((2, 3, 720, 1), np.float32)
    s = ConeSampler(X, np.isfinite(X), [0.0, 0.5, 1.0],
                    -180.0 + 0.5 * np.arange(720), ["ssh"], L_in=1,
                    dlat_deg=0.5)
    assert s.wrap is True


def test_north_atlantic_sample_is_bit_identical_to_before_the_wrap():
    """The window path did not move. Not "equivalent" — identical bytes.

    NA_DIGEST was taken from the sampler as it stood before this change; if
    the wrap, the `_read` indirection or the group routing altered ANY value,
    flag or coordinate on a non-wrapping tensor, this fails.
    """
    X, lats, lons = _na_fixture()
    s = ConeSampler(X, np.isfinite(X), lats, lons, NA_CHANS, L_in=6)
    assert s.wrap is False
    out = s.sample(_na_anchors())
    assert _digest(out) == NA_DIGEST, (
        "the North Atlantic sampling path changed. Every archived cone number "
        "was produced by the code this digest was taken from.")
    # and the edge anchors really did exercise the invalid branch, or the
    # comparison above is vacuous there
    assert not out["valid"][:4].all()


# ----------------------------------------------------- the global fixture --
GLOBAL_NY, GLOBAL_NX = 721, 1440


def _address_globe(T=8, chans=("ssh",)):
    """A global tensor in which every cell holds its own (row, col) address.

    `code = row * 1440 + col` is at most 1,038,239, well inside float32's
    exact integer range, so "the value that came back" and "the cell the cone
    named" are literally comparable — `tests/test_cone_dot_path.py`'s trick,
    one grid larger.
    """
    y = np.arange(GLOBAL_NY, dtype=np.float32)[:, None]
    x = np.arange(GLOBAL_NX, dtype=np.float32)[None, :]
    code = (y * GLOBAL_NX + x)
    X = np.repeat(np.repeat(code[None, :, :, None], len(chans), axis=3),
                  T, axis=0).astype(np.float32)
    lats = -90.0 + 0.25 * np.arange(GLOBAL_NY)
    lons = -180.0 + 0.25 * np.arange(GLOBAL_NX)
    return np.ascontiguousarray(X), lats, lons, list(chans)


def test_a_dot_at_lon_minus_179_75_reads_the_plus_179_side():
    """The anchor sits in column 1 (lon -179.75). Its westward dots leave the
    axis and must come back at columns near 1439, with the VALUE of those
    cells — not zero, not the value of column 0 clamped, and not invalid."""
    X, lats, lons, chans = _address_globe()
    s = ConeSampler(X, np.isfinite(X), lats, lons, chans, L_in=6)
    assert s.wrap is True
    y, x, t = 504, 1, 7                                   # lat 36, lon -179.75
    out = s.sample(np.array([[t, y, x]], np.int64))
    R = s.row(y)
    want_col = (x + R["dx"]) % GLOBAL_NX
    want_row = y + R["dy"]
    # every dot is on the grid: latitude never leaves it at 36 N and longitude
    # cannot leave it at all
    assert out["valid"][0].all()
    got = out["vals"][0, :R["n"]]
    assert np.array_equal(got, (want_row * GLOBAL_NX + want_col)
                          .astype(np.float32))
    # the wrap actually happened: some dots are far to the east
    assert (want_col > 1400).sum() > 0
    # and the EXACT cells, spelled out for the first family-B lag so a reader
    # can check the arithmetic by hand: dx = -8 at column 1 is column 1433.
    by_lag = {}
    for l, dy, dx in zip(R["lag"], R["dy"], R["dx"]):
        by_lag.setdefault(int(l), []).append([y + int(dy),
                                              (x + int(dx)) % GLOBAL_NX])
    assert by_lag[1] == [[504, 1], [505, 1], [502, 5], [504, 1433],
                         [507, 8], [498, 1439], [510, 1435]]
    assert all(0 <= c < GLOBAL_NX for cells in by_lag.values()
               for _, c in cells)


def test_the_same_anchor_on_a_window_is_invalid_where_the_globe_wraps():
    """The control. Give the identical cone a NON-closing axis of the same
    width and the westward dots are off the tensor and read as invalid — which
    is what family 4 does and must keep doing."""
    X, lats, lons, chans = _address_globe()
    # 1200 columns of 0.25 deg span 300 deg: the axis does NOT close, whatever
    # its first value is. (Any 1440-wide 0.25 deg axis does, which is why the
    # control has to be narrower rather than merely shifted.)
    nx = 1200
    win = ConeSampler(np.ascontiguousarray(X[:, :, :nx]),
                      np.isfinite(X[:, :, :nx]), lats, lons[:nx], chans,
                      L_in=6)
    assert win.wrap is False
    out = win.sample(np.array([[7, 504, 1]], np.int64))
    R = win.row(504)
    off = (1 + R["dx"] < 0) | (1 + R["dx"] >= nx)
    assert off.sum() > 0
    assert not out["valid"][0, :R["n"]][off].any()
    assert (out["vals"][0, :R["n"]][off] == 0).all()


def test_the_lag0_patch_wraps_too():
    """`_patch` is the other place a column offset is applied. At column 0 the
    3x3's west column is 1439, and all nine cells are real."""
    X, lats, lons, chans = _address_globe()
    s = ConeSampler(X, np.isfinite(X), lats, lons, chans, L_in=1)
    out = s.sample(np.array([[3, 400, 0]], np.int64))
    got = out["patch_vals"][0, 0]
    want = np.array([[(400 + dy) * GLOBAL_NX + ((0 + dx) % GLOBAL_NX)]
                     for dy in (-1, 0, 1) for dx in (-1, 0, 1)],
                    np.float32).ravel()
    assert np.array_equal(got, want)
    assert out["patch_obs"][0, 0].all()
    assert 399 * GLOBAL_NX + 1439 in set(got.tolist())


def test_latitude_is_clipped_never_wrapped():
    """There is no cell north of the pole. A dot that leaves the latitude axis
    stays invalid even on a globe — E-071 §1's own rule, and the reason the
    near-pole case is a MEASUREMENT in cone_geometry.json rather than a fix."""
    X, lats, lons, chans = _address_globe()
    s = ConeSampler(X, np.isfinite(X), lats, lons, chans, L_in=6)
    y = GLOBAL_NY - 3                                   # lat 89.5
    out = s.sample(np.array([[7, y, 700]], np.int64))
    R = s.row(y)
    off = (y + R["dy"] >= GLOBAL_NY) | (y + R["dy"] < 0)
    assert off.sum() > 0, "the polar anchor did not reach off the axis"
    assert not out["valid"][0, :R["n"]][off].any()
    # nothing wrapped round to the far side: no dot's row is negative-modulo
    rows = (y + R["dy"])[~off]
    assert rows.min() >= 0 and rows.max() < GLOBAL_NY


# ================================================== 2. the coarse lookup ==
def _toy_groups(nx=1440, ny=721, T=4):
    """A two-group set whose coarse array holds its own (y1, x1) address."""
    dense = np.zeros((T, ny, nx, 1), np.float32)
    ny1, nx1 = 181, 360
    y1 = np.arange(ny1, dtype=np.float32)[:, None]
    x1 = np.arange(nx1, dtype=np.float32)[None, :]
    coarse = np.repeat((y1 * nx1 + x1)[None, :, :, None], T,
                       axis=0).astype(np.float32)
    g0 = Group("g025", dense, -90.0 + 0.25 * np.arange(ny),
               -180.0 + 0.25 * np.arange(nx), ["ssh"])
    g1 = Group("g100", coarse, np.arange(-90.0, 91.0),
               np.arange(-180.0, 180.0), ["t2m"])
    return GroupSet([g0, g1])


def test_the_coarse_factor_is_derived_from_the_lat_steps():
    gs = _toy_groups()
    assert [g.factor for g in gs.groups] == [1, 4]
    # and a group whose step is not a whole multiple is refused rather than
    # rounded into the nearest cell
    # 240 rows from pole to pole is a step of 180/239 = 0.7531 deg, i.e.
    # 3.01 master cells — not a whole number, so there is no cell the lookup
    # could name and the set refuses rather than rounding to 3.
    bad = Group("g033", np.zeros((4, 240, 480, 1), np.float32),
                np.linspace(-90, 90, 240), np.linspace(-180, 179.25, 480),
                ["t2m"])
    with pytest.raises(ValueError, match="whole number"):
        GroupSet([gs.groups[0], bad])


def test_coarse_lookup_at_x_1439_lands_on_x1_zero():
    """E-070 §1: `x1 = floor(x/4 + 0.5) mod 360`. Columns 1438 and 1439 round
    to 360 and wrap to 0, which is the same meridian as +180 — the one case
    the plan calls out, and the one a `min(..., nx1-1)` clamp would get wrong
    by putting them at 359.
    """
    from build_family7 import coarse_lookup
    gs = _toy_groups()
    s = ConeSampler(gs, None, gs.lats, gs.lons, gs.chan, L_in=1)
    nx1 = 360
    for x, want_x1 in ((1439, 0), (1438, 0), (1436, 359), (0, 0), (2, 1),
                       (4, 1), (6, 2)):
        v, _ = s.read_cells(np.int64(1), np.int64(360), np.int64(x),
                            np.array([1], np.int64))
        y1 = 90                                    # row 360 -> lat 0 -> y1 90
        assert float(v[0]) == y1 * nx1 + want_x1, (x, want_x1)
        # and it is the BUILDER's own lookup, not a second one
        by, bx = coarse_lookup(np.array([360]), np.array([x]))
        assert (int(by[0]), int(bx[0])) == (y1, want_x1)


def test_the_lag0_patch_serves_one_coarse_cell_nine_times():
    """E-070 D3, "served as the same cell": a 1 degree field sampled at 0.25
    degrees does not gain resolution from a 3x3 of 0.25 degree cells. Away
    from a coarse boundary all nine patch cells are the same coarse value —
    and the token shape is unchanged, which is the point."""
    gs = _toy_groups()
    s = ConeSampler(gs, None, gs.lats, gs.lons, gs.chan, L_in=1)
    out = s.sample(np.array([[2, 360, 200]], np.int64))     # x=200 -> x1=50
    patch = out["patch_vals"][0, 1]                          # channel 1 = t2m
    assert patch.shape == (9,)
    assert len(set(patch.tolist())) == 1
    assert patch[0] == 90 * 360 + 50
    # the dense channel is NOT collapsed: nine distinct cells, nine values
    assert out["patch_vals"][0, 0].shape == (9,)


# ================================================ 3. the family-7 tensor ==
@pytest.fixture(scope="module")
def smoke_tensor(tmp_path_factory):
    """A REAL family-7 tensor: `ml/build_family7.py --smoke` writes synthetic
    sources through every stage of the production builder onto the full
    721 x 1440 grid, five pentad bins, in about twenty seconds."""
    import build_family7
    root = str(tmp_path_factory.mktemp("f7"))
    work = build_family7.run_smoke(root=root, keep=True)
    from tensor_io import load_tensor
    return load_tensor(os.path.join(work, build_family7.STEM + ".npz"))


@pytest.fixture(scope="module")
def smoke_sampler(smoke_tensor):
    d = smoke_tensor
    gs = GroupSet.from_tensor(d)
    return ConeSampler(gs, None, np.asarray(d["lats"]), np.asarray(d["lons"]),
                       gs.chan, L_in=2), gs, d


def test_the_groups_are_the_plan_s_three(smoke_sampler):
    s, gs, d = smoke_sampler
    assert gs.names == ["g025", "g100", "rg100"]
    assert [g.C for g in gs.groups] == [7, 15, 32]
    assert [g.factor for g in gs.groups] == [1, 4, 4]
    assert (s.T, s.H, s.W, s.C) == (5, 721, 1440, 54)
    assert s.wrap is True
    # the concatenated channel list IS what a value index means
    assert s.chan_names == ([str(c) for c in d["chan_g025"]]
                            + [str(c) for c in d["chan_g100"]]
                            + [str(c) for c in d["chan_rg100"]])
    # rg100 is a live-bins group and its rows are MASTER ROWS after the
    # translation through the npz's own absolute bin_index
    rows = np.asarray(gs.groups[2].bin_index)
    assert len(rows) == gs.groups[2].T
    absolute = np.asarray(d["rg_bin_index"], np.int64)
    master = np.asarray(d["bin_index"], np.int64)
    assert [int(master[r]) for r in rows if r >= 0] == \
        [int(b) for b in absolute if b in set(master.tolist())]


def test_the_token_count_is_cone_budget_unchanged(smoke_sampler):
    """The group change alters WHERE a value comes from, not how many tokens
    there are: one patch token per channel plus one per inner dot, exactly as
    `ml/cone.py::budget` computes it for the concatenated channel list."""
    s, gs, d = smoke_sampler
    for row in (200, 360, 504, 700):
        lat = float(s.lats[row])
        b = cone.budget(lat, s.chan_names, L_in=s.L_in, dlat_deg=0.25)
        assert b["n_channels"] == s.C == 54
        assert b["patch_tokens"] == s.C
        assert b["dot_tokens"] == s.n_dots(row)
        assert b["total_tokens"] == s.C + s.n_dots(row)
        # family L really is in there — its three land channels each carry
        # their own dots now, at every inner lag
        assert b["dots_per_family"]["L"] == 3 * len(
            cone.inner_dots(lat, "L", L_in=s.L_in))


def test_a_dot_over_land_reads_the_shared_channels_and_misses_the_ocean(
        smoke_sampler):
    """The whole point of family 7 (E-070's own line: *"the `slab[~ocean] =
    NaN` line of family 4 is gone: land is observed now"*).

    Over land the OBSERVED ocean channels have nothing — `cur_speed`, `ssh`
    and, since E-071 section 6.1's correction of 4 Sep, `sst` are NaN and must
    arrive as MISS tokens (observed False, value zeroed) — while the SHARED
    channels do: `skt` (the reanalysis surface temperature) and `t2m`, both
    from the coarse group, are finite and observed. Under family 4 this anchor
    had no channel that could be observed at all.
    """
    s, gs, d = smoke_sampler
    sphere = np.asarray(d["sphere"])
    cur = np.asarray(d["X_g025"][3, :, :, 0], np.float32)
    sst = np.asarray(d["X_g025"][3, :, :, 5], np.float32)
    land = (sphere == 1) & ~np.isfinite(cur) & ~np.isfinite(sst)
    ys, xs = np.nonzero(land)
    assert len(ys) > 100, "the smoke tensor has no land cell to test on"
    y, x = int(ys[len(ys) // 2]), int(xs[len(ys) // 2])

    out = s.sample(np.array([[4, y, x]], np.int64))
    R = s.row(y)
    idx = {n: i for i, n in enumerate(s.chan_names)}
    # the ANCHOR COLUMN dot at lag 1 — the same cell, one pentad back (bin 3)
    col = (R["lag"] == 1) & (R["dy"] == 0) & (R["dx"] == 0)
    for name, want_obs in (("skt", True), ("t2m", True),
                           ("cur_speed", False), ("ssh", False),
                           ("sst", False)):
        m = col & (R["chan"] == idx[name])
        assert m.sum() == 1, name
        j = int(np.flatnonzero(m)[0])
        assert bool(out["valid"][0, j]) is True, name
        assert bool(out["obs"][0, j]) is want_obs, name
        if not want_obs:
            # a miss token is a REAL token carrying zero, not an absent one
            assert out["vals"][0, j] == 0.0, name
        else:
            assert np.isfinite(out["vals"][0, j])
    # and the coarse channel came from the coarse cell, not from thin air
    from build_family7 import coarse_lookup
    y1, x1 = coarse_lookup(np.array([y]), np.array([x]))
    want = np.float32(np.asarray(d["X_g100"])[3, int(y1[0]), int(x1[0]),
                                              idx["t2m"] - 7])
    j = int(np.flatnonzero(col & (R["chan"] == idx["t2m"]))[0])
    assert out["vals"][0, j] == want


def test_rg_values_appear_only_at_live_bins(smoke_sampler):
    """`rg100` holds one row per month, written into the pentad containing the
    15th. Every other bin must be a miss token — never the nearest month's
    profile, which is what indexing the group by bin would silently give."""
    s, gs, d = smoke_sampler
    rows = np.asarray(gs.groups[2].bin_index)
    live = sorted({int(r) for r in rows if r >= 0})
    assert live, "the smoke tensor wrote no live rg bin"
    idx = {n: i for i, n in enumerate(s.chan_names)}
    ci = np.array([idx["rg_t300"]], np.int64)
    # a cell RG actually covers: inside its -64.5..79.5 band, and finite
    arr = np.asarray(d["X_rg100"][0, :, :, 0], np.float32)
    ys, xs = np.nonzero(np.isfinite(arr))
    assert len(ys), "rg100 is entirely NaN in the smoke tensor"
    y1, x1 = int(ys[len(ys) // 2]), int(xs[len(ys) // 2])
    y, x = y1 * 4, x1 * 4                     # a master cell that looks it up

    for t in range(s.T):
        v, o = s.read_cells(np.int64(t), np.int64(y), np.int64(x), ci)
        if t in live:
            assert np.isfinite(v[0]) and bool(o[0]), t
        else:
            assert not np.isfinite(v[0]) and not bool(o[0]), t
    # through `sample` the same bins are miss tokens with a zero value. The
    # anchor bin has to be >= 1 or the lag-1 dot is off the TIME axis, which
    # is a different kind of absence (invalid, not unobserved).
    # ...and the bin the LAG-1 dot lands on has to be dead too, or the test
    # is asserting about a live bin one step back.
    dead = [t for t in range(1, s.T) if t not in live and (t - 1) not in live]
    assert dead, "the smoke tensor has no two consecutive dead rg bins"
    out = s.sample(np.array([[dead[0], y, x]], np.int64))
    R = s.row(y)
    j = int(np.flatnonzero((R["chan"] == idx["rg_t300"])
                           & (R["dy"] == 0) & (R["dx"] == 0)
                           & (R["lag"] == 1))[0])
    assert out["valid"][0, j]              # the dot EXISTS
    assert not out["obs"][0, j]            # the data does not
    assert out["vals"][0, j] == 0.0


def test_group_time_gives_a_live_bins_group_its_own_months(smoke_sampler):
    """`rg100`'s row r belongs to master row `bin_index[r]`, so the anomaly
    transform must be handed THAT row's calendar month. Handing it the
    master's arrays would charge every profile to the wrong climatology."""
    s, gs, d = smoke_sampler
    months = [str(m) for m in d["months"]]
    moy = np.array([int(m[5:7]) - 1 for m in months])
    t_hold = np.zeros(len(months), bool)
    t_hold[0] = True
    for g in gs.groups:
        gmoy, ghold = group_time(g, moy, t_hold)
        assert len(gmoy) == len(ghold) == g.T
        if g.bin_index is None:
            assert np.array_equal(gmoy, moy)
            assert np.array_equal(ghold, t_hold)
        else:
            rows = np.asarray(g.bin_index)
            for r, (mm, hh) in enumerate(zip(gmoy, ghold)):
                if rows[r] >= 0:
                    assert mm == moy[rows[r]]
                    assert bool(hh) == bool(t_hold[rows[r]])
                else:
                    assert bool(hh) is True      # unreachable rows are held out


def test_export_family7_matches_a_direct_sample(smoke_tensor, tmp_path):
    """The exporter's whole claim, on the global tensor: the flags and values
    in the file are `ConeSampler.sample`'s, bit for bit — the same assertion
    `tests/test_export_cone_sample.py` makes for family 4, on the path where
    the values now come out of three arrays instead of one."""
    import json
    import export_cone_sample as X
    d = smoke_tensor
    stem = d.path
    out = str(tmp_path / "out")
    written = X.main(["--tensor", stem, "--out", out, "--start", "2010-01-18",
                      "--n-dates", "2", "--outer-stride", "40",
                      "--anomaly", "none",
                      "--anchors", "dateline,sahara"])
    assert len(written) == 2

    gs = GroupSet.from_tensor(d)
    s = ConeSampler(gs, None, np.asarray(d["lats"]), np.asarray(d["lons"]),
                    gs.chan, L_in=6)
    for anc, path, text in written:
        j = json.loads(text)
        m = j["meta"]
        assert m["grid"] == dict(ny=721, nx=1440, lat0=-90.0, lon0=-180.0,
                                 step=0.25, wrap=True)
        assert m["groups"]["names"] == ["g025", "g100", "rg100"]
        assert m["channel_group"]["cur_speed"] == "g025"
        assert m["channel_group"]["t2m"] == "g100"
        assert m["channel_group"]["rg_t300"] == "rg100"
        assert m["recipe"] == "f7l0"
        assert m["sphere_at_anchor"] in (0, 1, 2, 3)
        assert m["elev_at_anchor"] is not None
        y, x = m["anchor"]["row"], m["anchor"]["col"]
        got = s.sample(np.array([[t, y, x] for t in
                                 [int(np.searchsorted(
                                     np.asarray(d["bin_index"], np.int64), b))
                                  for b in m["bins"]]], np.int64))
        n = s.n_dots(y)
        assert n == j["inner"]["n_dots"]
        assert X.bits(got["valid"][:, :n]) == j["inner"]["valid"]
        assert X.bits(got["obs"][:, :n]) == j["inner"]["obs"]
        assert X.bits(got["patch_obs"]) == j["patch"]["obs"]
        assert X.bits(got["fut_obs"]) == j["future"]["obs"]
        assert [[X.sig(v) for v in r] for r in got["vals"][:, :n]] \
            == j["inner"]["raw"]
        # the outer stencil wrapped on the global grid: every column is on it
        assert all(0 <= c < 1440 for c in j["outer"]["col"])
        assert set(j["outer"]["valid"]) == {"1"}
    # the dateline anchor is the last column and its cone crosses it
    dl = json.loads(next(t for a, p, t in written if a["id"] == "dateline"))
    assert dl["meta"]["anchor"]["col"] == 1439
    assert min(dl["inner"]["col"]) < 40
    assert max(dl["inner"]["col"]) > 1400


if __name__ == "__main__":                                  # pragma: no cover
    raise SystemExit(pytest.main([__file__, "-q"]))
